title: Tin's Home Page
logo: /assets/img/Logo.PNG
#description: text below image
#show_downloads: true
#author:
#name             : "Tin Hang"
#bio              : "Multimodal learning"
location         : "CA, USA"
#employer         : "California Social Services" 
#email            : "lastancientone@gmail.com" 
#linkelin         : "https://www.linkedin.com/in/tin-hang/"
#github           : "LastAncientOne"
theme: jekyll-theme-minmal

