#title: Tin's Home Page
#logo: /assets/img/Logo.PNG
#description: text below image
#show_downloads: true
#theme: jekyll-theme-minimal

# Site settings
title: Tin's Home Page
logo: /assets/img/Logo.PNG
author:
  name: Tin Hang
  links:
    - title: LinkedIn
      url: https://www.linkedin.com/in/tin-hang/
    - title: Email
      url: mailto:lastancientone@gmail.com
    - title: GitHub
      url: https://github.com/LastAncientOne
theme: jekyll-theme-minimal
