#title: Tin's Home Page
#logo: /assets/img/Logo.PNG
#description: text below image
#show_downloads: true
#theme: jekyll-theme-minimal

# Site settings
# Site settings
title: Tin's Home Page
logo: /assets/img/Logo.PNG
social:
  linkedin: https://www.linkedin.com/in/tin-hang/
  email: mailto:lastancientone@gmail.com
  github: https://github.com/LastAncientOne
theme: jekyll-theme-minimal
